name: Build and upload with compose

on:
  push:
    branches: 
      - main
    paths:
      - compose.yaml

  pull_request:
    branches:
      - main
    paths:
      - compose.yaml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Checkout repository
      run: |
        docker compose build
        docker login ghcr.io -u Nemethlorin -p ${{ secrets.GITHUB_TOKEN }}
        docker compose push